# Generated by Django 5.0.2 on 2024-04-17 12:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qualities', '0002_alter_hobby_name_alter_hobby_slug_education'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Candidate')),
                ('education', models.ManyToManyField(to='qualities.education', verbose_name='Education')),
            ],
        ),
    ]
