# Generated by Django 5.0.2 on 2024-04-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.SmallIntegerField(default=0, verbose_name='Last N (0 for none)'),
        ),
    ]
