# Generated by Django 5.0.2 on 2024-04-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_alter_resume_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='include_address',
            field=models.BooleanField(default=True, verbose_name='Include Address'),
        ),
        migrations.AddField(
            model_name='resume',
            name='include_contact_number',
            field=models.BooleanField(default=True, verbose_name='Include Contact Number'),
        ),
        migrations.AddField(
            model_name='resume',
            name='include_email_id',
            field=models.BooleanField(default=True, verbose_name='Include Email ID'),
        ),
        migrations.AddField(
            model_name='resume',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Educational qualifications (recent N, 0 for none)'),
        ),
    ]
