# Generated by Django 5.0.2 on 2024-04-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('resumes', '0004_resume_include_address_resume_include_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='target_company',
            field=models.ManyToManyField(to='companies.company', verbose_name='Target Companies'),
        ),
    ]
