# Generated by Django 5.0.2 on 2024-04-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_resume_target_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='name'),
        ),
    ]
