# Generated by Django 5.0.2 on 2024-04-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualities', '0006_alter_skill_category'),
        ('resumes', '0006_resume_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skill',
            field=models.ManyToManyField(to='qualities.skill', verbose_name='Skills'),
        ),
    ]
