# Generated by Django 5.0.2 on 2024-04-23 21:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_softskill_resume_soft_skills_technicalskill_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='softskill',
            name='category',
            field=models.CharField(choices=[('team_management', 'Team Management'), ('communication', 'Communication'), ('leadership', 'Leadership'), ('problem_solving', 'Problem Solving'), ('adaptability', 'Adaptability'), ('time_management', 'Time Management'), ('conflict_resolution', 'Conflict Resolution'), ('teamwork', 'Teamwork'), ('negotiation', 'Negotiation'), ('creativity', 'Creativity'), ('decision_making', 'Decision Making'), ('mentoring', 'Mentoring'), ('stress_management', 'Stress Management')], default='other', max_length=25, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='softskill',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='softskill',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='technicalskill',
            name='category',
            field=models.CharField(choices=[('programming_language', 'Programming Language'), ('frameworks', 'Frameworks and Libraries'), ('version_control', 'Version Control Systems'), ('methodologies', 'Development Methodologies'), ('data_analysis', 'Data Analysis and Analytics'), ('it_networking', 'IT and Networking'), ('web_dev_design', 'Web Development and Design'), ('ai_ml', 'Machine Learning and Artificial Intelligence'), ('dbms', 'Database Management'), ('cloud_computing', 'Cloud Computing'), ('devops', 'DevOps'), ('other', 'Other')], default='other', max_length=25, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='technicalskill',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='technicalskill',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='technicalskill',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='softskill',
            name='candidate',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Candidate'),
        ),
        migrations.AlterField(
            model_name='softskill',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='technicalskill',
            name='candidate',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Candidate'),
        ),
        migrations.AlterField(
            model_name='technicalskill',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
