# Generated by Django 5.0.2 on 2024-04-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_resume_skill'),
        ('resumes', '0008_softskill_category_softskill_slug_and_more'),
    ]

    operations = [
    ]
