# Generated by Django 5.0.2 on 2024-04-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_merge_20240424_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='skill',
        ),
    ]
