# Generated by Django 5.0.2 on 2024-05-07 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_full_name'),
        ('resumes', '0010_remove_resume_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
