# Generated by Django 5.0.2 on 2024-04-17 14:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('address', models.TextField(verbose_name='address')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('contact_numbers', models.CharField(blank=True, max_length=100, verbose_name='contact_numbers')),
            ],
        ),
    ]
