# Generated by Django 5.0.2 on 2024-04-17 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('education_level', models.CharField(choices=[('primary', 'primary'), ('middle_school', 'middle_school'), ('high_school', 'high_school'), ('higher_secondary', 'higher_secondary'), ('graduation', 'graduation'), ('post_graduation', 'post_graduation'), ('doctorate', 'doctorate'), ('post_doctorate', 'post_doctorate'), ('diploma', 'diploma'), ('course', 'course'), ('other', 'other')], max_length=20, verbose_name='Level')),
                ('institute', models.CharField(max_length=150, verbose_name='Institute')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Additional Info')),
                ('date_of_passing', models.DateTimeField(null=True, verbose_name='Date of Passing')),
                ('pursuing', models.BooleanField(default=False, verbose_name='Pursuing')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Candidate')),
            ],
        ),
    ]
