# Generated by Django 5.0.2 on 2024-04-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualities', '0003_skill_hobby_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming_language', 'Programming Language'), ('frameworks', 'Frameworks and Libraries'), ('version_control', 'Version Control Systems'), ('methodologies', 'Development Methodologies'), ('data_analysis', 'Data Analysis and Analytics'), ('it_networking', 'IT and Networking'), ('web_dev_design', 'Web Development and Design'), ('ai_ml', 'Machine Learning and Artificial Intelligence'), ('dbms', 'Database Management'), ('cloud_computing', 'Cloud Computing'), ('devops', 'DevOps'), ('team_management', 'Team Management'), ('communication', 'Communication'), ('leadership', 'Leadership'), ('problem_solving', 'Problem Solving'), ('adaptability', 'Adaptability'), ('time_management', 'Time Management'), ('conflict_resolution', 'Conflict Resolution'), ('teamwork', 'Teamwork'), ('negotiation', 'Negotiation'), ('creativity', 'Creativity'), ('decision_making', 'Decision Making'), ('mentoring', 'Mentoring'), ('stress_management', 'Stress Management')], max_length=25, verbose_name='Category'),
        ),
    ]
