# Generated by Django 5.0.2 on 2024-04-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualities', '0005_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming_language', 'Programming Language'), ('frameworks', 'Frameworks and Libraries'), ('version_control', 'Version Control Systems'), ('methodologies', 'Development Methodologies'), ('data_analysis', 'Data Analysis and Analytics'), ('it_networking', 'IT and Networking'), ('web_dev_design', 'Web Development and Design'), ('ai_ml', 'Machine Learning and Artificial Intelligence'), ('dbms', 'Database Management'), ('cloud_computing', 'Cloud Computing'), ('devops', 'DevOps'), ('other', 'Other')], default='other', max_length=25, verbose_name='Category'),
        ),
    ]
