# Generated by Django 5.0.2 on 2024-04-23 20:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualities', '0006_alter_skill_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('team_management', 'Team Management'), ('communication', 'Communication'), ('leadership', 'Leadership'), ('problem_solving', 'Problem Solving'), ('adaptability', 'Adaptability'), ('time_management', 'Time Management'), ('conflict_resolution', 'Conflict Resolution'), ('teamwork', 'Teamwork'), ('negotiation', 'Negotiation'), ('creativity', 'Creativity'), ('decision_making', 'Decision Making'), ('mentoring', 'Mentoring'), ('stress_management', 'Stress Management')], max_length=25, verbose_name='Category')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soft_skills', to=settings.AUTH_USER_MODEL, verbose_name='Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('programming_language', 'Programming Language'), ('frameworks', 'Frameworks and Libraries'), ('version_control', 'Version Control Systems'), ('methodologies', 'Development Methodologies'), ('data_analysis', 'Data Analysis and Analytics'), ('it_networking', 'IT and Networking'), ('web_dev_design', 'Web Development and Design'), ('ai_ml', 'Machine Learning and Artificial Intelligence'), ('dbms', 'Database Management'), ('cloud_computing', 'Cloud Computing'), ('devops', 'DevOps'), ('other', 'Other')], default='other', max_length=25, verbose_name='Category')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_skills', to=settings.AUTH_USER_MODEL, verbose_name='Candidate')),
            ],
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
