# Generated by Django 5.0.2 on 2024-05-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualities', '0007_softskill_technicalskill_delete_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='education_level',
            field=models.CharField(choices=[('primary', 'primary'), ('middle_school', 'middle_school'), ('high_school', 'high_school'), ('higher_secondary', 'higher_secondary'), ('graduation', 'graduation'), ('post_graduation', 'post_graduation'), ('doctorate', 'doctorate'), ('post_doctorate', 'post_doctorate'), ('diploma', 'diploma'), ('course', 'course'), ('other', 'other')], max_length=50, verbose_name='Level'),
        ),
    ]
