# Generated by Django 5.0.2 on 2024-05-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualities', '0010_alter_education_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date_of_passing',
            field=models.DateField(null=True, verbose_name='Date of Passing'),
        ),
    ]
